services:
  server:
    container_name: python-scraper
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    command: ["flask", "run", "--debug", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - REMOTE_DRIVER=http://standalone-chrome-7qfu.onrender.com
